### ISSUE TITLE
How to I delete a storage policy in Kubernetes? Using Prototyped Admission controller plugin for storage policy management

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#137]
1. What is the current problem?

- Till now we completely rely on kubernetes to issue a request to the vSphere cloud provider for volume management. All our volume management code resides in our implementation to the Kubernetes cloud provider interface. For example, consider our newly designed vSphere SPBM storage policy management feature where the user specifies the policy parameters in the storage class definition. Right now, we defer the policy creation until a PVC is created which is not the right user experience at all. 

- As a user, I want the policy to be created immediately after the storage class is created. (GOOD USER EXPERIENCE). But the problem is CREATE/DELETE storage class request doesn't generate a request to the vSphere Cloud provider interface where we manage all our code.

- So, inorder to overcome this problem we need a way to intercept the storage class API request before it gets provisioned successfully on the Kubernetes API SERVER. For this, we move onto Kubernetes admissions controller plugins which will help us achieve this functionality. Inorder to accomplish some advanced features in Kubernetes, we require an admission control plug-in to be enabled in order to properly support the feature. As a result, a Kubernetes API server that is not properly configured with the right set of admission control plug-ins is an incomplete server and will not support all the features you expect.

2. Let's take a use case.

- When the user wants to create a storage class with SPBM policy attributes. User creates a storage class with storage policy attributes.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: Prodspbmpolicy
provisioner: kubernetes.io/vsphere-volume
parameters:
  hostFailuresToTolerate: 2
  proportionalCapacity:1
```

- The STORAGECLASS CREATE request will be intercepted by our new admission controller plugin we have written and will create a SPBM policy out of it which in this case is "spbmpolicy".
Here we create a SPBM policy with the same name as the storage class.
The storage class is a global entity in a kubernetes cluster and hence its name is unique in a single cluster.

- If the user creates a storage class with the same name in a different kubernetes cluster, we have 2 options. We either error out to the user that a SPBM policy is already created. Please use a different name (I think this is not a good USER EXPERIENCE). Append, storageclassName with some UNIQUE_ID for a cluster, that helps differentiate storage classes with the same name across multiple kubernetes cluster. (This is a good user experience but have to identify what UNIQUE_ID can be used that is unique for a cluster).

- User creates a PVC with the above created storage class.
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: policy-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: Prodspbmpolicy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```
The vSphere cloud provider will create a persistent volume with the policy configured with "Prodspbmpolicy" Name already created on the VC.
