### ISSUE TITLE
Photon PD volume plugin: support persistent disk name as parameter for volume source

### ISSUE THREAD

**Issue by luomiao** [vmware/kubernetes#23]
Current acceptable API:
```
  volumes:
  - name: photon-storage-1
    photonPersistentDisk:
        pdID: "cd1e1fe4-2da3-4546-a036-95eabede818a"
```
We want to also support:
```
  volumes:
  - name: photon-storage-1
    photonPersistentDisk:
        pdName: "data-disk"
```

In PC platform, the disk name is not unique. When more than one disk with the required name are existing, we should return an error message and request for ID of the disk.
