### ISSUE TITLE
PV attachment causes VM to hang

### ISSUE THREAD

**Issue by bradbeam** [vmware/kubernetes#502]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:

When a pod is rescheduled and volumes are moved from one VM to another, we're seeing approx 25s of unresponsiveness per volume attachment. 

**What you expected to happen**:

Volume attachment/detachment happens seamlessly without interrupting / pausing the node. 

**How to reproduce it (as minimally and precisely as possible)**:

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pvctest
  name: pvctest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvctest
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pvctest
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: pvctest
        resources: {}
        volumeMounts:
        - mountPath: /pvc1
          name: pvc1
        - mountPath: /pvc2
          name: pvc2
        - mountPath: /pvc3
          name: pvc3
        - mountPath: /pvc4
          name: pvc4
        - mountPath: /pvc5
          name: pvc5
        - mountPath: /pvc6
          name: pvc6
        - mountPath: /pvc7
          name: pvc7
        - mountPath: /pvc8
          name: pvc8
        - mountPath: /pvc9
          name: pvc9
      dnsPolicy: ClusterFirst
      volumes:
      - name: pvc1
        persistentVolumeClaim:
          claimName: pvctest1
      - name: pvc2
        persistentVolumeClaim:
          claimName: pvctest2
      - name: pvc3
        persistentVolumeClaim:
          claimName: pvctest3
      - name: pvc4
        persistentVolumeClaim:
          claimName: pvctest4
      - name: pvc5
        persistentVolumeClaim:
          claimName: pvctest5
      - name: pvc6
        persistentVolumeClaim:
          claimName: pvctest6
      - name: pvc7
        persistentVolumeClaim:
          claimName: pvctest7
      - name: pvc8
        persistentVolumeClaim:
          claimName: pvctest8
      - name: pvc9
        persistentVolumeClaim:
          claimName: pvctest9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvctest
  name: pvctest1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvctest
  name: pvctest2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvctest
  name: pvctest3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvctest
  name: pvctest4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvctest
  name: pvctest5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvctest
  name: pvctest6
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvctest
  name: pvctest7
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvctest
  name: pvctest8
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvctest
  name: pvctest9
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

On the first deployment everything seems to come up fine. After deleting the running pod, we experience the behavior. 

```
ubuntu@s01-mgmt01:~/brad$ kubectl get pods -n brad -o wide
NAME                       READY     STATUS              RESTARTS   AGE       IP        NODE
pvctest-69998f46c6-rs5qc   0/1       ContainerCreating   0          51s       <none>    s01-k8s01.cluster.local
ubuntu@s01-mgmt01:~/brad$ ping s01-pyrex01
PING s01-k8s01.cluster.local (10.0.0.20) 56(84) bytes of data.
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=1 ttl=64 time=17340 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=2 ttl=64 time=16341 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=3 ttl=64 time=15341 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=4 ttl=64 time=14341 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=5 ttl=64 time=13341 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=6 ttl=64 time=12341 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=7 ttl=64 time=11341 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=8 ttl=64 time=10341 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=9 ttl=64 time=9341 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=10 ttl=64 time=8342 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=11 ttl=64 time=7342 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=12 ttl=64 time=6342 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=13 ttl=64 time=5342 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=14 ttl=64 time=4342 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=15 ttl=64 time=3342 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=16 ttl=64 time=2342 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=17 ttl=64 time=1342 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=18 ttl=64 time=342 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=19 ttl=64 time=0.235 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=20 ttl=64 time=0.272 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=21 ttl=64 time=23123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=22 ttl=64 time=22123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=23 ttl=64 time=21123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=24 ttl=64 time=20123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=25 ttl=64 time=19123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=26 ttl=64 time=18123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=27 ttl=64 time=17123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=28 ttl=64 time=16123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=29 ttl=64 time=15123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=30 ttl=64 time=14123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=31 ttl=64 time=13123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=32 ttl=64 time=12123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=33 ttl=64 time=11123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=34 ttl=64 time=10123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=35 ttl=64 time=9123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=36 ttl=64 time=8123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=37 ttl=64 time=7123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=38 ttl=64 time=6123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=39 ttl=64 time=5123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=40 ttl=64 time=4123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=41 ttl=64 time=3123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=42 ttl=64 time=2123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=43 ttl=64 time=1123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=44 ttl=64 time=123 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=45 ttl=64 time=0.239 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=46 ttl=64 time=0.287 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=47 ttl=64 time=0.250 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=48 ttl=64 time=0.273 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=49 ttl=64 time=0.199 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=50 ttl=64 time=0.261 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=51 ttl=64 time=0.271 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=52 ttl=64 time=0.241 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=53 ttl=64 time=0.317 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=54 ttl=64 time=0.254 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=55 ttl=64 time=14894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=56 ttl=64 time=13894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=57 ttl=64 time=12894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=58 ttl=64 time=11894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=59 ttl=64 time=10894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=60 ttl=64 time=9894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=61 ttl=64 time=8894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=62 ttl=64 time=7894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=63 ttl=64 time=6894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=64 ttl=64 time=5894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=65 ttl=64 time=4894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=66 ttl=64 time=3894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=67 ttl=64 time=2894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=68 ttl=64 time=1894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=69 ttl=64 time=894 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=70 ttl=64 time=0.192 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=71 ttl=64 time=24935 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=72 ttl=64 time=23927 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=73 ttl=64 time=22919 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=74 ttl=64 time=21911 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=75 ttl=64 time=20903 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=76 ttl=64 time=19896 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=77 ttl=64 time=18888 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=78 ttl=64 time=17880 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=79 ttl=64 time=16872 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=80 ttl=64 time=15864 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=81 ttl=64 time=14856 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=82 ttl=64 time=13848 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=83 ttl=64 time=12840 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=84 ttl=64 time=11832 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=85 ttl=64 time=10824 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=86 ttl=64 time=9816 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=87 ttl=64 time=8808 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=88 ttl=64 time=7800 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=89 ttl=64 time=6792 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=90 ttl=64 time=5784 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=91 ttl=64 time=4776 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=92 ttl=64 time=3770 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=93 ttl=64 time=2763 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=94 ttl=64 time=1755 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=95 ttl=64 time=747 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=96 ttl=64 time=0.247 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=97 ttl=64 time=0.251 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=98 ttl=64 time=0.213 ms
64 bytes from s01-k8s01.cluster.local (10.0.0.20): icmp_seq=99 ttl=64 time=0.254 ms
```

```
Events:
  Type     Reason                  Age   From                                            Message
  ----     ------                  ----  ----                                            -------
  Normal   Scheduled               3m    default-scheduler                               Successfully assigned pvctest-64b5d5cb96-h6jxh to s01-k8s05.cluster.local
  Warning  FailedAttachVolume      3m    attachdetach-controller                         AttachVolume.Attach failed for volume "pvc-f9026429-a642-11e8-8ef3-005056a3dca5" : Failed to add disk 'scsi1:8'.
  Warning  FailedAttachVolume      3m    attachdetach-controller                         AttachVolume.Attach failed for volume "pvc-f9054441-a642-11e8-8ef3-005056a3dca5" : Failed to add disk 'scsi1:8'.
  Warning  FailedAttachVolume      2m    attachdetach-controller                         AttachVolume.Attach failed for volume "pvc-f911e697-a642-11e8-8ef3-005056a3dca5" : Failed to add disk 'scsi1:8'.
  Warning  FailedAttachVolume      2m    attachdetach-controller                         AttachVolume.Attach failed for volume "pvc-f9080a65-a642-11e8-8ef3-005056a3dca5" : Failed to add disk 'scsi1:8'.
  Warning  FailedAttachVolume      1m    attachdetach-controller                         AttachVolume.Attach failed for volume "pvc-f90033b5-a642-11e8-8ef3-005056a3dca5" : Failed to add disk 'scsi1:8'.
  Warning  FailedAttachVolume      1m    attachdetach-controller                         AttachVolume.Attach failed for volume "pvc-f90989d1-a642-11e8-8ef3-005056a3dca5" : Failed to add disk 'scsi1:8'.
  Warning  FailedAttachVolume      58s   attachdetach-controller                         AttachVolume.Attach failed for volume "pvc-f90e9d37-a642-11e8-8ef3-005056a3dca5" : Failed to add disk 'scsi1:8'.
  Warning  FailedAttachVolume      32s   attachdetach-controller                         AttachVolume.Attach failed for volume "pvc-f90cb795-a642-11e8-8ef3-005056a3dca5" : Failed to add disk 'scsi1:8'.
  Warning  FailedAttachVolume      6s    attachdetach-controller                         AttachVolume.Attach failed for volume "pvc-f9141b6b-a642-11e8-8ef3-005056a3dca5" : Failed to add disk 'scsi1:8'.
  Warning  FailedMount             1m    kubelet, s01-k8s05.cluster.local  Unable to mount volumes for pod "pvctest-64b5d5cb96-h6jxh_default(e4136d7d-a651-11e8-82ea-005056a3dca5)": timeout expired waiting for volumes to attach or mount for pod "default"/"pvctest-64b5d5cb96-h6jxh". list of unmounted volumes=[pvc1 pvc2 pvc3 pvc4 pvc5 pvc6 pvc7 pvc8 pvc9 default-token-82j8x]. list of unattached volumes=[pvc1 pvc2 pvc3 pvc4 pvc5 pvc6 pvc7 pvc8 pvc9 default-token-82j8x]
  Normal   SuccessfulAttachVolume  6s    attachdetach-controller                         AttachVolume.Attach succeeded for volume "pvc-f9026429-a642-11e8-8ef3-005056a3dca5"
  Normal   SuccessfulAttachVolume  5s    attachdetach-controller                         AttachVolume.Attach succeeded for volume "pvc-f9054441-a642-11e8-8ef3-005056a3dca5"
  Normal   SuccessfulMountVolume   5s    kubelet, s01-k8s05.cluster.local  MountVolume.SetUp succeeded for volume "default-token-82j8x"
  Normal   SuccessfulAttachVolume  5s    attachdetach-controller                         AttachVolume.Attach succeeded for volume "pvc-f911e697-a642-11e8-8ef3-005056a3dca5"
  Normal   SuccessfulAttachVolume  5s    attachdetach-controller                         AttachVolume.Attach succeeded for volume "pvc-f9080a65-a642-11e8-8ef3-005056a3dca5"
  Normal   SuccessfulAttachVolume  4s    attachdetach-controller                         AttachVolume.Attach succeeded for volume "pvc-f90033b5-a642-11e8-8ef3-005056a3dca5"
  Normal   SuccessfulAttachVolume  4s    attachdetach-controller                         AttachVolume.Attach succeeded for volume "pvc-f90989d1-a642-11e8-8ef3-005056a3dca5"
  Normal   SuccessfulAttachVolume  3s    attachdetach-controller                         AttachVolume.Attach succeeded for volume "pvc-f90e9d37-a642-11e8-8ef3-005056a3dca5"
  Normal   SuccessfulMountVolume   3s    kubelet, s01-k8s05.cluster.local  MountVolume.SetUp succeeded for volume "pvc-f911e697-a642-11e8-8ef3-005056a3dca5"
  Normal   SuccessfulAttachVolume  3s    attachdetach-controller                         AttachVolume.Attach succeeded for volume "pvc-f90cb795-a642-11e8-8ef3-005056a3dca5"
  Normal   SuccessfulAttachVolume  2s    attachdetach-controller                         AttachVolume.Attach succeeded for volume "pvc-f9141b6b-a642-11e8-8ef3-005056a3dca5"
  Normal   SuccessfulMountVolume   0s    kubelet, s01-k8s05.cluster.local  MountVolume.SetUp succeeded for volume "pvc-f9141b6b-a642-11e8-8ef3-005056a3dca5"
```
I changed the order of the above slightly to reflect the time; FailedMount shows up with a 1m timestamp, but didn't appear until after the last FailedAttachVolume. 
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
ubuntu@puc-pyrex-mgmt01:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6+coreos.0", GitCommit:"c2aac694c2c7373dfe3ad81f47fc3cbc70a5a8fa", GitTreeState:"clean", BuildDate:"2018-03-21T21:54:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: 
vSphere 6.5

- OS (e.g. from /etc/os-release):
```
ubuntu@puc-pyrex-mgmt01:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

- Kernel (e.g. `uname -a`):
```
Linux s01-mgmt01.cluster.local 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
Kubespray

- Others:
